image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2

stages:
  - deploy

before_script:
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - eval "$(ssh-agent -s)"
  - ssh-add ~/.ssh/id_rsa
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config

deploy:
  stage: deploy
  only:
    - master
  script:
    - echo "Deploying React+Vite to EC2 via docker-compose"

    # Prepara la cartella remota
    - ssh ubuntu@$EC2_HOST "rm -rf ~/frontend && mkdir ~/frontend"

    # Copia tutto il necessario sul server EC2
    - scp -r ./* ubuntu@$EC2_HOST:/home/ubuntu/frontend/

    # Esegui il build e deploy via Docker Compose
    - ssh ubuntu@$EC2_HOST "
        cd /home/ubuntu/frontend &&
        docker compose down || true &&
        docker compose build &&
        docker compose up -d
      "